# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LayerTOCSV
                                 A QGIS plugin
 this plugin saves a given layer  into  a csv
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-07-08
        copyright            : (C) 2021 by Couse-Geospatial AI
        email                : juniorkachann@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load LayerTOCSV class from file LayerTOCSV.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Save_Attr import LayerTOCSV
    return LayerTOCSV(iface)
